# Generated by Django 4.0.5 on 2022-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sys_recipe',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
