# Generated by Django 4.0.5 on 2022-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_sys_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
