# Generated by Django 4.1 on 2022-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_alter_food_food_group_alter_food_quantitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_group",
            field=models.CharField(
                choices=[
                    ("CARBOHYDRATES", "CARBOHYDRATES"),
                    ("VITAMINS", "VITAMINS"),
                    ("FATS", "FATS"),
                    ("PROTEINS", "PROTEINS"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="quantitation",
            field=models.CharField(
                choices=[
                    ("ltr", "ltr"),
                    ("bunch", "bunch"),
                    ("kg", "kg"),
                    ("oz", "oz"),
                    ("piece", "piece"),
                    ("ml", "ml"),
                    ("g", "g"),
                    ("packet", "packet"),
                ],
                max_length=32,
            ),
        ),
    ]
